

import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link
            rel="stylesheet"
            type="text/css"
            // charset="UTF-8"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
          />
          <link
            rel="stylesheet"
            type="text/css"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
          />
          <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />

      </head>

      <body className={` ${manrope.className} bg-[#F8F7F3]`}>
        {children}

        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
           <script>
            AOS.init();
          </script>
        </body>
        
    </html>
  );
}
