

import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer";
import Header from "@/components/header/Header";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link
            rel="stylesheet"
            type="text/css"
            // charset="UTF-8"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
          />
          <link
            rel="stylesheet"
            type="text/css"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
          />
      </head>

      <body className={`${manrope.className} bg-[#F8F7F3]`}>

        
        <Header/>
      
        {children}
        <Footer/>
     


        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

        </body>
        
    </html>
  );
}
