

import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer";
import Header from "@/components/header/Header";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        
        <Header/>
      
        {children}
        <Footer/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

        </body>
        
    </html>
  );
}
